### ISSUE TITLE
readme file links

### ISSUE THREAD

**Issue by JoanaFMorgado** [simphony/SimNanoDOME#1]
Dear Giorgio.

After going through the readme file I would like to suggest changing some of the provided links.

For the the compatibility section I propose the following changes:
  - Replace `OSP-core` link by : https://github.com/simphony/osp-core
  - Replace link to OSP-core releases by : https://github.com/simphony/osp-core/releases
  
Many thanks!

@pablo-de-andres (FYI)

Kind Regards,
Joana

**Comment by glc8** [comment]
Dear Joana,

i changed the links as you suggested. This time (i don't know why) i need for @pablo-de-andres approval to finalize the change in README.md file.

Have a nice day,
GLC

**Comment by giorgiolacivita** [comment]
Links changed. Sorry it was my fault, i was using the wrong account.
